version: '3'

services:
  web:
    build: .
    env_file:
      - '.env'
    ports:
      - '5000:5000'
    volumes:
      - '.:/var/www/html'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'rabibot'
      MYSQL_USER: 'rabibot'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - rabibot-db:/var/lib/mysql
volumes:
  rabibot-db:
